// ─── constants/routeMeta.js ──────────────────────────────────────────────────
// Route metadata registry driving dynamic Layout headers, Sidebars, and Breadcrumbs.
// Document reference: Document 10 — Route Structure §3

import {
  LayoutDashboard,
  Briefcase,
  Users,
  Calendar,
  Building2,
  Bell,
  BookmarkCheck,
  FileText,
  User,
  Search,
} from 'lucide-react';
import { ROUTES } from './routes.js';
import { ROLES } from './roles.js';

export const ROUTE_META = {
  // ── Recruiter Protected Routes ───────────────────
  [ROUTES.RECRUITER.DASHBOARD]: {
    title: 'Dashboard',
    icon: LayoutDashboard,
    roles: [ROLES.RECRUITER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard'],
  },
  [ROUTES.RECRUITER.JOBS]: {
    title: 'Job Postings',
    icon: Briefcase,
    roles: [ROLES.RECRUITER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard', 'Jobs'],
  },
  [ROUTES.RECRUITER.JOB_NEW]: {
    title: 'Post New Job',
    icon: Briefcase,
    roles: [ROLES.RECRUITER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: false,
    breadcrumb: ['Dashboard', 'Jobs', 'New'],
  },
  [ROUTES.RECRUITER.JOB_EDIT]: {
    title: 'Edit Job',
    icon: Briefcase,
    roles: [ROLES.RECRUITER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: false,
    breadcrumb: ['Dashboard', 'Jobs', ':jobTitle', 'Edit'],
  },
  [ROUTES.RECRUITER.JOB_PIPELINE]: {
    title: 'Job Pipeline',
    icon: Users,
    roles: [ROLES.RECRUITER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: false,
    breadcrumb: ['Dashboard', 'Jobs', ':jobTitle'],
  },
  [ROUTES.RECRUITER.CANDIDATE_DETAIL]: {
    title: 'Candidate Profile',
    icon: User,
    roles: [ROLES.RECRUITER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: false,
    breadcrumb: ['Dashboard', 'Candidates', ':candidateName'],
  },
  [ROUTES.RECRUITER.INTERVIEWS]: {
    title: 'Interviews',
    icon: Calendar,
    roles: [ROLES.RECRUITER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard', 'Interviews'],
  },
  [ROUTES.RECRUITER.COMPANY]: {
    title: 'Company Profile',
    icon: Building2,
    roles: [ROLES.RECRUITER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard', 'Company'],
  },
  [ROUTES.RECRUITER.NOTIFICATIONS]: {
    title: 'Notifications',
    icon: Bell,
    roles: [ROLES.RECRUITER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard', 'Notifications'],
  },

  // ── Hiring Manager Protected Routes ───────────────
  [ROUTES.HM.DASHBOARD]: {
    title: 'Dashboard',
    icon: LayoutDashboard,
    roles: [ROLES.HIRING_MANAGER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard'],
  },
  [ROUTES.HM.JOBS]: {
    title: 'My Jobs',
    icon: Briefcase,
    roles: [ROLES.HIRING_MANAGER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard', 'Jobs'],
  },
  [ROUTES.HM.JOB_PIPELINE]: {
    title: 'Job Pipeline',
    icon: Users,
    roles: [ROLES.HIRING_MANAGER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: false,
    breadcrumb: ['Dashboard', 'Jobs', ':jobTitle'],
  },
  [ROUTES.HM.CANDIDATE_DETAIL]: {
    title: 'Candidate Evaluation',
    icon: User,
    roles: [ROLES.HIRING_MANAGER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: false,
    breadcrumb: ['Dashboard', 'Jobs', ':jobTitle', ':candidateName'],
  },
  [ROUTES.HM.NOTIFICATIONS]: {
    title: 'Notifications',
    icon: Bell,
    roles: [ROLES.HIRING_MANAGER],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard', 'Notifications'],
  },

  // ── Candidate Protected Routes ──────────────────
  [ROUTES.CANDIDATE.DASHBOARD]: {
    title: 'Dashboard',
    icon: LayoutDashboard,
    roles: [ROLES.CANDIDATE],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard'],
  },
  [ROUTES.CANDIDATE.APPLICATIONS]: {
    title: 'My Applications',
    icon: FileText,
    roles: [ROLES.CANDIDATE],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard', 'Applications'],
  },
  [ROUTES.CANDIDATE.APPLICATION_DETAIL]: {
    title: 'Application Progress',
    icon: FileText,
    roles: [ROLES.CANDIDATE],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: false,
    breadcrumb: ['Dashboard', 'Applications', ':jobTitle'],
  },
  [ROUTES.CANDIDATE.SAVED_JOBS]: {
    title: 'Saved Jobs',
    icon: BookmarkCheck,
    roles: [ROLES.CANDIDATE],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard', 'Saved Jobs'],
  },
  [ROUTES.CANDIDATE.PROFILE]: {
    title: 'My Profile',
    icon: User,
    roles: [ROLES.CANDIDATE],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard', 'Profile'],
  },
  [ROUTES.CANDIDATE.NOTIFICATIONS]: {
    title: 'Notifications',
    icon: Bell,
    roles: [ROLES.CANDIDATE],
    requiresAuth: true,
    layout: 'dashboard',
    showInSidebar: true,
    breadcrumb: ['Dashboard', 'Notifications'],
  },

  // ── Public Routes ──────────────────────────────
  [ROUTES.HOME]: {
    title: 'Careers',
    icon: null,
    roles: [],
    requiresAuth: false,
    layout: 'public',
    showInSidebar: false,
    breadcrumb: ['Home'],
    meta: {
      title: 'TalentFlow — Recruitment Management Platform',
      description: 'Find your next career opportunity and apply to premium positions.',
    },
  },
  [ROUTES.JOBS]: {
    title: 'Careers Board',
    icon: Briefcase,
    roles: [],
    requiresAuth: false,
    layout: 'public',
    showInSidebar: false,
    breadcrumb: ['Home', 'Careers'],
    meta: {
      title: 'Explore Careers — TalentFlow',
      description: 'Search and filter open jobs at premium companies on our global board.',
    },
  },
  [ROUTES.JOB_DETAIL]: {
    title: 'Job Post Detail',
    icon: Briefcase,
    roles: [],
    requiresAuth: false,
    layout: 'public',
    showInSidebar: false,
    breadcrumb: ['Home', 'Careers', ':jobTitle'],
    meta: {
      title: 'Job Position Details — TalentFlow',
      description: 'View responsibilities, requirements, and submit application files.',
    },
  },
  [ROUTES.LOGIN]: {
    title: 'Login',
    icon: null,
    roles: [],
    requiresAuth: false,
    layout: 'public',
    showInSidebar: false,
    breadcrumb: ['Home', 'Login'],
    meta: {
      title: 'Sign In — TalentFlow',
      description: 'Log in to your recruiter, hiring manager, or candidate account.',
    },
  },
  [ROUTES.REGISTER]: {
    title: 'Create Account',
    icon: null,
    roles: [],
    requiresAuth: false,
    layout: 'public',
    showInSidebar: false,
    breadcrumb: ['Home', 'Register'],
    meta: {
      title: 'Register Profile — TalentFlow',
      description: 'Create a candidate profile to apply or track recruitment pipelines.',
    },
  },
  [ROUTES.SEARCH]: {
    title: 'Search Board',
    icon: Search,
    roles: [],
    requiresAuth: false,
    layout: 'public',
    showInSidebar: false,
    breadcrumb: ['Home', 'Search'],
    meta: {
      title: 'Global Search — TalentFlow',
      description: 'Search jobs and dashboard pathways across TalentFlow.',
    },
  },
};

Object.freeze(ROUTE_META);
